# Purpose

This notebook validates the first raw-to-staging transformation in the GCP Data Engineering Project.

The objective is to confirm that the dbt staging model preserves the source row count and correctly converts priority fields from the raw BigQuery table into analytics-ready data types.

The checks focus on:

- raw-to-staging row-count consistency;
- failed date parsing;
- failed numeric conversions;
- failed boolean conversions;
- unexpected nulls in required fields; and
- duplicate records based on a candidate flight-level grain.

This notebook is not part of the production pipeline. It is a development and validation artifact used to support model design decisions before building downstream fact and mart models.

# Environment/Context

This validation was performed in Google BigQuery Notebooks against the development environment for the GCP Data Engineering Project.

Current pipeline state:

```text
Cloud Storage landing bucket
        ↓
BigQuery raw dataset
        ↓
dbt source declaration
        ↓
dbt staging model
        ↓
BigQuery analytics dataset

Query a staging table with SQL and magic commands

In [6]:
# Running this code will query a table in BigQuery and download
# the results to a Pandas DataFrame named `staging`.

%%bigquery staging --project exemplary-oath-501101-p8
SELECT * FROM `exemplary-oath-501101-p8.analytics_dataset.stg_bts_on_time_performance`

Query is running:   0%|          |

Downloading:   0%|          |

In [7]:
# View the results
staging.head()

,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,sch_op_carrier_fl_num,op_unique_carrier,origin_airport_id,origin_airport_seq_id,...,distance,distance_group,carrier_delay,weather_delay,nas_delay,security_delay,first_dep_time,total_add_gtime,longest_add_gtime,div_airport_landings
0,1.000000000,1.000000000,16.000000000,5.000000000,2026-01-16,AA,None,MQ,10792.000000000,1079206.000000000,...,296.000000000,2.000000000,0E-9,0E-9,0E-9,2.000000000,None,None,None,0E-9
1,1.000000000,1.000000000,16.000000000,5.000000000,2026-01-16,AA,None,MQ,10792.000000000,1079206.000000000,...,474.000000000,2.000000000,2.000000000,0E-9,0E-9,0E-9,None,None,None,0E-9
2,1.000000000,1.000000000,16.000000000,5.000000000,2026-01-16,AA,None,MQ,10792.000000000,1079206.000000000,...,474.000000000,2.000000000,6.000000000,0E-9,1.000000000,0E-9,None,None,None,0E-9
3,1.000000000,1.000000000,16.000000000,5.000000000,2026-01-16,AA,None,MQ,10821.000000000,1082106.000000000,...,622.000000000,3.000000000,None,None,None,None,None,None,None,0E-9
4,1.000000000,1.000000000,16.000000000,5.000000000,2026-01-16,AA,None,MQ,10821.000000000,1082106.000000000,...,622.000000000,3.000000000,0E-9,0E-9,16.000000000,0E-9,None,None,None,0E-9

In [8]:
# Does the same as above for the raw data into a dataframe name raw
%%bigquery raw --project exemplary-oath-501101-p8
SELECT * FROM `exemplary-oath-501101-p8.raw_dataset.raw_airline_ontime_performance`

Query is running:   0%|          |

Downloading:   0%|          |

In [9]:
raw.head()

,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,SCH_OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,...,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS
0,1,1,1,4,1/1/2026 12:00:00 AM,AA,None,AA,10140,1014006,...,569.00,3,None,None,None,None,None,None,None,0
1,1,1,1,4,1/1/2026 12:00:00 AM,AA,None,AA,10140,1014006,...,569.00,3,None,None,None,None,None,None,None,0
2,1,1,1,4,1/1/2026 12:00:00 AM,AA,None,AA,10140,1014006,...,569.00,3,2021.00,0.00,0.00,0.00,None,None,None,0
3,1,1,1,4,1/1/2026 12:00:00 AM,AA,None,AA,10140,1014006,...,569.00,3,None,None,None,None,None,None,None,0
4,1,1,1,4,1/1/2026 12:00:00 AM,AA,None,AA,10140,1014006,...,569.00,3,0.00,0.00,0.00,0.00,None,None,None,0

# Validation Steps
1. Row and column count match
2. Date parsing
3. Numeric conversions
4. Boolean conversions
5. Candidate Grain Duplicates

# Step 1: Row and column count validation

In [10]:
# Step 1: Check that row and column count match
# Returns True if both row and column counts match
# Staging has intentionally preserved all columns from the raw dataset, so the column count should match

dimensions_match = staging.shape == raw.shape

print("Staging Shape:")
print(staging.shape)
print("Raw Shape:")
print(raw.shape)
print("Shape Validation Passed? ",dimensions_match)

Staging Shape:
(602953, 62)
Raw Shape:
(602953, 62)
Shape Validation Passed?  True

# Step 2: Date Parsing Validation
This validation is intentionally light. It is assumed that if null count matches, the parsing was successful.

### Note on validation structure

The numeric conversion checks are intentionally written as separate validation cells rather than abstracted into a reusable function.

Because this notebook is a one-off validation artifact for the first staging model, duplicating a small amount of code made the checks easier to read, review, and troubleshoot. If these checks become recurring validation logic, they should be refactored into reusable functions or promoted into dbt tests.

In [11]:
# Step 2: Validate date parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_null_fl_dates = raw['FL_DATE'].isnull().any()
staging_null_fl_dates =  staging['fl_date'].isnull().any()
fl_parse_successful = raw_null_fl_dates == staging_null_fl_dates

print("Raw flight date nulls: ", raw_null_fl_dates)
print("Staging flight date nulls: ", staging_null_fl_dates)
print("Flight date parse successful? ",fl_parse_successful)

Raw flight date nulls:  False
Staging flight date nulls:  False
Flight date parse successful?  True

# Step 3: Numeric Parsing Validation
The same assumption of null value count applies to this step, as well.

In [12]:
# Step 3a: Validate quarter parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_null_quarter = raw['QUARTER'].isnull().any()
staging_null_quarter =  staging['quarter'].isnull().any()
quarter_parse_successful = raw_null_quarter == staging_null_quarter

print("Raw quarter nulls: ", raw_null_quarter)
print("Staging quarter nulls: ", staging_null_quarter)
print("Quarter parse successful? ",quarter_parse_successful)

Raw quarter nulls:  False
Staging quarter nulls:  False
Quarter parse successful?  True

In [13]:
# Step 3b: Validate date parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_null_quarter = raw['QUARTER'].isnull().any()
staging_null_quarter =  staging['quarter'].isnull().any()
quarter_parse_successful = raw_null_quarter == staging_null_quarter

print("Raw quarter nulls: ", raw_null_quarter)
print("Staging quarter nulls: ", staging_null_quarter)
print("Quarter parse successful? ",quarter_parse_successful)

Raw quarter nulls:  False
Staging quarter nulls:  False
Quarter parse successful?  True

In [14]:
# Step 3c: Validate month parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_null_month = raw['MONTH'].isnull().any()
staging_null_month =  staging['month'].isnull().any()
month_parse_successful = raw_null_month == staging_null_month

print("Raw month nulls: ", raw_null_month)
print("Staging month nulls: ", staging_null_month)
print("month parse successful? ",month_parse_successful)

Raw month nulls:  False
Staging month nulls:  False
month parse successful?  True

In [15]:
# Step 3d: Validate day of month parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_column = "DAY_OF_MONTH"
staging_column = "day_of_month"

raw_null_dayofmonth = raw[raw_column].isnull().any()
staging_null_dayofmonth =  staging[staging_column].isnull().any()
dayofmonth_parse_successful = raw_null_dayofmonth == staging_null_dayofmonth

print("Raw month nulls: ", raw_null_dayofmonth)
print("Staging month nulls: ", staging_null_dayofmonth)
print("Day of month parse successful? ",dayofmonth_parse_successful)

Raw month nulls:  False
Staging month nulls:  False
Day of month parse successful?  True

In [16]:
# Step 3e: Validate day of week parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_column = "DAY_OF_WEEK"
staging_column = "day_of_week"

raw_null_dayofweek = raw[raw_column].isnull().any()
staging_null_dayofweek =  staging[staging_column].isnull().any()
dayofweek_parse_successful = raw_null_dayofweek == staging_null_dayofweek

print("Raw month nulls: ", raw_null_dayofweek)
print("Staging month nulls: ", staging_null_dayofweek)
print("Day of month parse successful? ",dayofweek_parse_successful)

Raw month nulls:  False
Staging month nulls:  False
Day of month parse successful?  True

# Step 4: Boolean Conversion Validation

In [24]:
# Step 4a: Validate DIVERTED parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_column = "DIVERTED"
staging_column = "is_diverted"

raw_null_diverted = raw[raw_column].isnull().any()
staging_null_diverted =  staging[staging_column].isnull().any()
diverted_parse_successful = raw_null_diverted == staging_null_diverted

print("Raw DIVERTED nulls: ", raw_null_diverted)
print("Staging is_diverted nulls: ", staging_null_diverted)
print("DIVERTED parse successful? ",diverted_parse_successful)

Raw DIVERTED nulls:  False
Staging is_diverted nulls:  False
DIVERTED parse successful?  True

In [26]:
# Step 4b: Validate CANCELLED parsing by checking for null values
# This should return false for the raw and staging dataset
# While not fully validated, the number of nulls matching is sufficient for this analysis

raw_column = "CANCELLED"
staging_column = "is_cancelled"

raw_null_cancelled = raw[raw_column].isnull().any()
staging_null_cancelled =  staging[staging_column].isnull().any()
cancelled_parse_successful = raw_null_cancelled == staging_null_cancelled

print("Raw cancelled nulls: ", raw_null_cancelled)
print("Staging is_cancelled nulls: ", staging_null_cancelled)
print("CANCELLED parse successful? ",cancelled_parse_successful)

Raw cancelled nulls:  False
Staging is_cancelled nulls:  False
CANCELLED parse successful?  True

# Step 5: Check for candidate grain duplicates

In [30]:
# Check for exact duplicate rows
dup_count = staging.duplicated().sum()
print(dup_count)

0

In [32]:
# Check unique combination of fl_date, op_unique_carrier, sch_op_carrier_fl_num,origin, dest, and crs_dep_time
is_composite_dup = staging.duplicated(subset=['fl_date', 'op_unique_carrier','sch_op_carrier_fl_num','origin','dest','crs_dep_time']).any()
if is_composite_dup:
  print("Candidate grain has duplicates.")
  print(staging[staging.duplicated(subset=['fl_date', 'op_unique_carrier','sch_op_carrier_fl_num','origin','dest','crs_dep_time'], keep=False)])
else:
  print("Candidate grain is unique.")

Candidate grain has duplicates.
            quarter        month  day_of_month  day_of_week     fl_date  \
1584    1.000000000  1.000000000  16.000000000  5.000000000  2026-01-16
2230    1.000000000  1.000000000  16.000000000  5.000000000  2026-01-16
2231    1.000000000  1.000000000  16.000000000  5.000000000  2026-01-16
2232    1.000000000  1.000000000  16.000000000  5.000000000  2026-01-16
2246    1.000000000  1.000000000  16.000000000  5.000000000  2026-01-16
...             ...          ...           ...          ...         ...
590943  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15
590958  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15
590983  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15
591035  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15
593624  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15

       mkt_unique_carrier sch_op_carrier_fl_num op_unique_carrier  \
1584                   AA                  None                OO
2230                   AA                  None                YX
2231                   AA                  None                YX
2232                   AA                  None                YX
2246                   AA                  None                YX
...                   ...                   ...               ...
590943                 DL                  None                YX
590958                 DL                  None                YX
590983                 DL                  None                YX
591035                 DL                  None                YX
593624                 UA                  None                OO

       origin_airport_id origin_airport_seq_id  ...       distance  \
1584     13930.000000000     1393008.000000000  ...  409.000000000
2230     10721.000000000     1072103.000000000  ...  184.000000000
2231     10721.000000000     1072103.000000000  ...  184.000000000
2232     10721.000000000     1072103.000000000  ...  184.000000000
2246     10792.000000000     1079206.000000000  ...  292.000000000
...                  ...                   ...  ...            ...
590943   12478.000000000     1247805.000000000  ...  187.000000000
590958   12953.000000000     1295304.000000000  ...  184.000000000
590983   12953.000000000     1295304.000000000  ...  214.000000000
591035   13930.000000000     1393008.000000000  ...  733.000000000
593624   13930.000000000     1393008.000000000  ...  409.000000000

       distance_group carrier_delay weather_delay     nas_delay  \
1584      2.000000000          0E-9  95.000000000  43.000000000
2230      1.000000000          None          None          None
2231      1.000000000          None          None          None
2232      1.000000000          None          None          None
2246      2.000000000          None          None          None
...               ...           ...           ...           ...
590943    1.000000000          None          None          None
590958    1.000000000          None          None          None
590983    1.000000000          None          None          None
591035    3.000000000          None          None          None
593624    2.000000000          None          None          None

       security_delay first_dep_time total_add_gtime longest_add_gtime  \
1584             0E-9           None            None              None
2230             None           None            None              None
2231             None           None            None              None
2232             None           None            None              None
2246             None           None            None              None
...               ...            ...             ...               ...
590943           None           None            None              None
590958           None           None            None              None
590983           None           None            None              None
591035           None           None            None              None
593624           None           None            None              None

       div_airport_landings
1584                   0E-9
2230                   0E-9
2231                   0E-9
2232                   0E-9
2246                   0E-9
...                     ...
590943                 0E-9
590958                 0E-9
590983                 0E-9
591035                 0E-9
593624                 0E-9

[594 rows x 62 columns]

In [34]:
# Adding mkt_unique_carrier, crs_arr_time, and dup
is_new_composite_dup = staging.duplicated(subset=['fl_date', 'op_unique_carrier','sch_op_carrier_fl_num','origin','dest','crs_dep_time','mkt_unique_carrier','crs_arr_time','dup']).any()
if is_new_composite_dup:
  print("Candidate grain has duplicates.")
  print(staging[staging.duplicated(subset=['fl_date', 'op_unique_carrier','sch_op_carrier_fl_num','origin','dest','crs_dep_time','mkt_unique_carrier','crs_arr_time','dup'], keep=False)])
else:
  print("Candidate grain is unique.")

Candidate grain has duplicates.
            quarter        month  day_of_month  day_of_week     fl_date  \
40088   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
40089   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
40097   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
40098   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
40182   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
40183   1.000000000  1.000000000  18.000000000  7.000000000  2026-01-18
59483   1.000000000  1.000000000  19.000000000  1.000000000  2026-01-19
59484   1.000000000  1.000000000  19.000000000  1.000000000  2026-01-19
59751   1.000000000  1.000000000  19.000000000  1.000000000  2026-01-19
59752   1.000000000  1.000000000  19.000000000  1.000000000  2026-01-19
107441  1.000000000  1.000000000   1.000000000  4.000000000  2026-01-01
107442  1.000000000  1.000000000   1.000000000  4.000000000  2026-01-01
108062  1.000000000  1.000000000   1.000000000  4.000000000  2026-01-01
108063  1.000000000  1.000000000   1.000000000  4.000000000  2026-01-01
127002  1.000000000  1.000000000   2.000000000  5.000000000  2026-01-02
127003  1.000000000  1.000000000   2.000000000  5.000000000  2026-01-02
167533  1.000000000  1.000000000  22.000000000  4.000000000  2026-01-22
167534  1.000000000  1.000000000  22.000000000  4.000000000  2026-01-22
245538  1.000000000  1.000000000  26.000000000  1.000000000  2026-01-26
245539  1.000000000  1.000000000  26.000000000  1.000000000  2026-01-26
471604  1.000000000  1.000000000   9.000000000  5.000000000  2026-01-09
471605  1.000000000  1.000000000   9.000000000  5.000000000  2026-01-09
491052  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
491053  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
491065  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
491066  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
491142  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
491143  1.000000000  1.000000000  10.000000000  6.000000000  2026-01-10
509020  1.000000000  1.000000000  11.000000000  7.000000000  2026-01-11
509021  1.000000000  1.000000000  11.000000000  7.000000000  2026-01-11
509337  1.000000000  1.000000000  11.000000000  7.000000000  2026-01-11
509338  1.000000000  1.000000000  11.000000000  7.000000000  2026-01-11
529161  1.000000000  1.000000000  12.000000000  1.000000000  2026-01-12
529162  1.000000000  1.000000000  12.000000000  1.000000000  2026-01-12
529760  1.000000000  1.000000000  12.000000000  1.000000000  2026-01-12
529761  1.000000000  1.000000000  12.000000000  1.000000000  2026-01-12
566643  1.000000000  1.000000000  14.000000000  3.000000000  2026-01-14
566644  1.000000000  1.000000000  14.000000000  3.000000000  2026-01-14
585415  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15
585416  1.000000000  1.000000000  15.000000000  4.000000000  2026-01-15

       mkt_unique_carrier sch_op_carrier_fl_num op_unique_carrier  \
40088                  AS                  None                AS
40089                  AS                  None                AS
40097                  AS                  None                AS
40098                  AS                  None                AS
40182                  AS                  None                AS
40183                  AS                  None                AS
59483                  AS                  None                AS
59484                  AS                  None                AS
59751                  AS                  None                AS
59752                  AS                  None                AS
107441                 AS                  None                AS
107442                 AS                  None                AS
108062                 AS                  None                AS
108063                 AS                  None                AS
127002                 AS                  None                AS
127003                 AS                  None                AS
167533                 AS                  None                AS
167534                 AS                  None                AS
245538                 AS                  None                AS
245539                 AS                  None                AS
471604                 AS                  None                AS
471605                 AS                  None                AS
491052                 AS                  None                AS
491053                 AS                  None                AS
491065                 AS                  None                AS
491066                 AS                  None                AS
491142                 AS                  None                AS
491143                 AS                  None                AS
509020                 AS                  None                AS
509021                 AS                  None                AS
509337                 AS                  None                AS
509338                 AS                  None                AS
529161                 AS                  None                AS
529162                 AS                  None                AS
529760                 AS                  None                AS
529761                 AS                  None                AS
566643                 AS                  None                AS
566644                 AS                  None                AS
585415                 AS                  None                AS
585416                 AS                  None                AS

       origin_airport_id origin_airport_seq_id  ...        distance  \
40088    12173.000000000     1217305.000000000  ...  2603.000000000
40089    12173.000000000     1217305.000000000  ...  2603.000000000
40097    12173.000000000     1217305.000000000  ...  2677.000000000
40098    12173.000000000     1217305.000000000  ...  2677.000000000
40182    12889.000000000     1288904.000000000  ...  2762.000000000
40183    12889.000000000     1288904.000000000  ...  2762.000000000
59483    12173.000000000     1217305.000000000  ...  2677.000000000
59484    12173.000000000     1217305.000000000  ...  2677.000000000
59751    14057.000000000     1405703.000000000  ...  2603.000000000
59752    14057.000000000     1405703.000000000  ...  2603.000000000
107441   12173.000000000     1217305.000000000  ...  2762.000000000
107442   12173.000000000     1217305.000000000  ...  2762.000000000
108062   14771.000000000     1477104.000000000  ...  2398.000000000
108063   14771.000000000     1477104.000000000  ...  2398.000000000
127002   12889.000000000     1288904.000000000  ...  2762.000000000
127003   12889.000000000     1288904.000000000  ...  2762.000000000
167533   12173.000000000     1217305.000000000  ...  2677.000000000
167534   12173.000000000     1217305.000000000  ...  2677.000000000
245538   12173.000000000     1217305.000000000  ...  2614.000000000
245539   12173.000000000     1217305.000000000  ...  2614.000000000
471604   12173.000000000     1217305.000000000  ...  2762.000000000
471605   12173.000000000     1217305.000000000  ...  2762.000000000
491052   12173.000000000     1217305.000000000  ...  2603.000000000
491053   12173.000000000     1217305.000000000  ...  2603.000000000
491065   12173.000000000     1217305.000000000  ...  2398.000000000
491066   12173.000000000     1217305.000000000  ...  2398.000000000
491142   12889.000000000     1288904.000000000  ...  2762.000000000
491143   12889.000000000     1288904.000000000  ...  2762.000000000
509020   14057.000000000     1405703.000000000  ...  2603.000000000
509021   14057.000000000     1405703.000000000  ...  2603.000000000
509337   14771.000000000     1477104.000000000  ...  2398.000000000
509338   14771.000000000     1477104.000000000  ...  2398.000000000
529161   12173.000000000     1217305.000000000  ...  2603.000000000
529162   12173.000000000     1217305.000000000  ...  2603.000000000
529760   14771.000000000     1477104.000000000  ...  2398.000000000
529761   14771.000000000     1477104.000000000  ...  2398.000000000
566643   12173.000000000     1217305.000000000  ...  2603.000000000
566644   12173.000000000     1217305.000000000  ...  2603.000000000
585415   14057.000000000     1405703.000000000  ...  2603.000000000
585416   14057.000000000     1405703.000000000  ...  2603.000000000

       distance_group carrier_delay weather_delay nas_delay security_delay  \
40088    11.000000000          None          None      None           None
40089    11.000000000          None          None      None           None
40097    11.000000000          None          None      None           None
40098    11.000000000  24.000000000          0E-9      0E-9           0E-9
40182    11.000000000          None          None      None           None
40183    11.000000000          None          None      None           None
59483    11.000000000          None          None      None           None
59484    11.000000000          None          None      None           None
59751    11.000000000          None          None      None           None
59752    11.000000000  27.000000000          0E-9      0E-9           0E-9
107441   11.000000000          None          None      None           None
107442   11.000000000          None          None      None           None
108062   10.000000000          None          None      None           None
108063   10.000000000          None          None      None           None
127002   11.000000000          None          None      None           None
127003   11.000000000  94.000000000          0E-9      0E-9           0E-9
167533   11.000000000          None          None      None           None
167534   11.000000000  24.000000000          0E-9      0E-9           0E-9
245538   11.000000000          None          None      None           None
245539   11.000000000          None          None      None           None
471604   11.000000000          None          None      None           None
471605   11.000000000  27.000000000          0E-9      0E-9           0E-9
491052   11.000000000          None          None      None           None
491053   11.000000000  18.000000000          0E-9      0E-9   14.000000000
491065   10.000000000          None          None      None           None
491066   10.000000000  30.000000000          0E-9      0E-9           0E-9
491142   11.000000000          None          None      None           None
491143   11.000000000          None          None      None           None
509020   11.000000000          None          None      None           None
509021   11.000000000          None          None      None           None
509337   10.000000000          None          None      None           None
509338   10.000000000          None          None      None           None
529161   11.000000000          None          None      None           None
529162   11.000000000          None          None      None           None
529760   10.000000000          None          None      None           None
529761   10.000000000          None          None      None           None
566643   11.000000000          None          None      None           None
566644   11.000000000          None          None      None           None
585415   11.000000000          None          None      None           None
585416   11.000000000          None          None      None           None

       first_dep_time total_add_gtime longest_add_gtime div_airport_landings
40088            None            None              None                 0E-9
40089            None            None              None                 0E-9
40097            None            None              None                 0E-9
40098            None            None              None                 0E-9
40182            None            None              None                 0E-9
40183            None            None              None                 0E-9
59483            None            None              None                 0E-9
59484            None            None              None                 0E-9
59751            None            None              None                 0E-9
59752            None            None              None                 0E-9
107441           None            None              None                 0E-9
107442           None            None              None                 0E-9
108062           None            None              None                 0E-9
108063           None            None              None                 0E-9
127002           None            None              None                 0E-9
127003           None            None              None                 0E-9
167533           None            None              None                 0E-9
167534           None            None              None                 0E-9
245538           None            None              None                 0E-9
245539           None            None              None                 0E-9
471604           None            None              None                 0E-9
471605           None            None              None                 0E-9
491052           None            None              None                 0E-9
491053           None            None              None                 0E-9
491065           None            None              None                 0E-9
491066           None            None              None                 0E-9
491142           None            None              None                 0E-9
491143           None            None              None                 0E-9
509020           None            None              None                 0E-9
509021           None            None              None                 0E-9
509337           None            None              None                 0E-9
509338           None            None              None                 0E-9
529161           None            None              None                 0E-9
529162           None            None              None                 0E-9
529760           None            None              None                 0E-9
529761           None            None              None                 0E-9
566643           None            None              None                 0E-9
566644           None            None              None                 0E-9
585415           None            None              None                 0E-9
585416           None            None              None                 0E-9

[40 rows x 62 columns]

In [39]:
# Testing new key
is_new_composite_dup = staging.duplicated(subset=['fl_date','mkt_unique_carrier','op_unique_carrier','origin_airport_seq_id','dest_airport_seq_id','crs_dep_time','crs_arr_time','dup','is_cancelled']).any()
if is_new_composite_dup:
  print("Candidate grain has duplicates.")
  display(staging[staging.duplicated(subset=['fl_date','mkt_unique_carrier','op_unique_carrier','origin_airport_seq_id','dest_airport_seq_id','crs_dep_time','crs_arr_time','dup','is_cancelled'], keep=False)])
else:
  print("Candidate grain is unique.")

Candidate grain is unique.

# Note on candidate key
The expanded natural key was not fully unique. Adding `is_cancelled` eliminated the remaining duplicate keys, but because cancellation status is an outcome field rather than an identifier, it was not selected as part of the natural grain. This supports using a generated surrogate key for the fact table while retaining the natural-key fields for analysis and validation.